
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2.console.enabled: true
  
cds:
  data-source.auto-config.enabled: false

logging:
  level:
    root: INFO
    customer.final_course_sap: DEBUG
    com.sap.cds: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  servlet:
    context-path: /
